ARG MICROARCH_LEVEL
FROM ghcr.io/rahilarious/gentoo:x86-64-${MICROARCH_LEVEL}

ARG BINHOST_URI
ARG PKG_NAME="net-dns/blocky"

RUN \
    --mount=type=tmpfs,tmpfs-size=100%,dst=/tmp \
    --mount=type=tmpfs,tmpfs-size=100%,dst=/var/tmp \
    --mount=type=tmpfs,tmpfs-size=100%,dst=/var/cache/edb \
    <<-EOF
    #!/usr/bin/bash

    set -e

    if [ -n "${BINHOST_URI}" ]; then
      echo '#####        Configuring binrepos.conf      ######'
    cat <<-EOT | tee -a /etc/portage/binrepos.conf/gentoo-on-steroids.conf
	[gentoo-on-steroids-binpkgserver]
	priority=100
	sync-uri=${BINHOST_URI}
	EOT
    fi

    emerge -vbgk --with-bdeps=y -o --quiet-build ${PKG_NAME}
    emerge -vBgk --with-bdeps=y --quiet-build ${PKG_NAME}
    emerge -c
    emerge -vKg --with-bdeps=n --quiet-build ${PKG_NAME}
    mkdir -pv /app/cache /logs
    chown -Rv blocky:blocky /app /logs

    ln -s /usr/bin/blocky /app/blocky

    echo '############         Cleaning up            #########'
    rm -rf /var/tmp/portage
    rm /var/log/emerge.log /var/log/portage/elog/summary.log
    truncate -s0 /var/log/emerge* /etc/portage/binrepos.conf/gentoo-on-steroids.conf

    echo '###########       CONGRATULATIONS !!! EVERYTHING SUCCESSFUL      #######'
EOF

USER blocky:blocky
WORKDIR /app

ENV BLOCKY_CONFIG_FILE=/app/config.yml

ENTRYPOINT ["/app/blocky"]

HEALTHCHECK --start-period=1m --timeout=3s CMD ["/app/blocky", "healthcheck"]
