ARG MICROARCH_LEVEL
FROM ghcr.io/rahilarious/gentoo:x86-64-${MICROARCH_LEVEL}

ARG BINHOST_URI
ARG PKG_NAME="net-dns/AdGuardHome"

RUN \
    --mount=type=tmpfs,tmpfs-size=100%,dst=/tmp \
    --mount=type=tmpfs,tmpfs-size=100%,dst=/var/tmp \
    \
    if [ -n "${BINHOST_URI}" ]; then \
      echo '#####        Configuring binrepos.conf      ######' && \
      { \
        echo '[binhost]'; \
        echo "priority=100"; \
        echo "sync-uri=${BINHOST_URI}"; \
      } >> /etc/portage/binrepos.conf/mybinhost.conf; \
    fi && \
    \
    emerge -vbgk --with-bdeps=y -o --quiet-build ${PKG_NAME} && \
    emerge -vBgk --with-bdeps=y --quiet-build ${PKG_NAME} && \
    emerge -c && \
    emerge -vKg --with-bdeps=n --quiet-build ${PKG_NAME} && \
    mkdir -pv /opt/adguardhome/{,conf,work} && \
    chown -R nobody: /opt/adguardhome && \
    chown nobody:nogroup /usr/bin/AdGuardHome && \
    ln -sv /usr/bin/AdGuardHome /opt/adguardhome/AdGuardHome && \
    \
    echo '############         Cleaning up            #########' && \
    rm -rf /var/tmp/portage && \
    rm /var/log/emerge.log /var/log/portage/elog/summary.log; \
    truncate -s0 /var/log/emerge* /etc/portage/binrepos.conf/mybinhost.conf && \
    \
    echo '###########       CONGRATULATIONS !!! EVERYTHING SUCCESSFUL      #######'


EXPOSE 53/tcp 53/udp 67/udp 68/udp 80/tcp 443/tcp 443/udp 853/tcp 853/udp 3000/tcp 3000/udp 5443/tcp 5443/udp 6060/tcp

WORKDIR /opt/adguardhome/work

ENTRYPOINT ["/opt/adguardhome/AdGuardHome"]

CMD [ "--no-check-update", "-c", "/opt/adguardhome/conf/AdGuardHome.yaml", "-w", "/opt/adguardhome/work" ]
