# syntax=docker/dockerfile:1

ARG MICROARCH_LEVEL
FROM ghcr.io/rahilarious/gentoo:x86-64-${MICROARCH_LEVEL}

ARG BINHOST_URI
ARG PKG_NAME="net-irc/thelounge"
ADD https://github.com/thelounge/thelounge-docker/raw/master/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh

RUN \
    --mount=type=tmpfs,tmpfs-size=100%,dst=/tmp \
    --mount=type=tmpfs,tmpfs-size=100%,dst=/var/tmp \
    --mount=type=tmpfs,tmpfs-size=100%,dst=/var/cache/edb \
    <<-EOF
    #!/usr/bin/bash
    set -e

    if [ -n "${BINHOST_URI}" ]; then
    echo '#####        Configuring binrepos.conf      ######'
    cat <<-EOT | tee -a /etc/portage/binrepos.conf/gentoo-on-steroids.conf
	[gentoo-on-steroids-binpkgserver]
	priority=100
	sync-uri=${BINHOST_URI}
	EOT
    fi

    emerge -vbgk --with-bdeps=y -o --quiet-build ${PKG_NAME}
    emerge -vBgk --with-bdeps=y --quiet-build  ${PKG_NAME}
    emerge -c
    emerge -vKg --with-bdeps=n --quiet-build ${PKG_NAME}

    # post install steps just for Container
    useradd -m -u 1000 -U node
    chmod -v 755 /usr/local/bin/docker-entrypoint.sh

    echo '############         Cleaning up            #########'
    rm -rf /var/tmp/portage
    truncate -s0 /etc/portage/binrepos.conf/gentoo-on-steroids.conf

    echo '###########       CONGRATULATIONS !!! EVERYTHING SUCCESSFUL      #######'
EOF

# https://github.com/thelounge/thelounge-docker/blob/master/Dockerfile
ENV THELOUNGE_HOME=/var/opt/thelounge PORT=9000
VOLUME "${THELOUNGE_HOME}"
EXPOSE ${PORT}

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["thelounge", "start"]
