# syntax=docker/dockerfile:1

ARG MICROARCH_LEVEL
FROM ghcr.io/rahilarious/gentoo:x86-64-${MICROARCH_LEVEL}

ARG BINHOST_URI
ARG PKG_NAME="net-p2p/syncthing"

RUN \
    --mount=type=tmpfs,tmpfs-size=100%,dst=/tmp \
    --mount=type=tmpfs,tmpfs-size=100%,dst=/var/tmp \
    --mount=type=tmpfs,tmpfs-size=100%,dst=/var/cache/edb \
    <<-EOF
    #!/usr/bin/bash

    set -e

    if [ -n "${BINHOST_URI}" ]; then
    echo '#####        Configuring binrepos.conf      ######'
    cat <<-EOT | tee -a /etc/portage/binrepos.conf/gentoo-on-steroids.conf
	[gentoo-on-steroids-binpkgserver]
	priority=100
	sync-uri=${BINHOST_URI}
	EOT
    fi

    emerge -vbgk --with-bdeps=y -o --quiet-build ${PKG_NAME}
    emerge -vBgk --with-bdeps=y --quiet-build ${PKG_NAME}
    emerge -c
    emerge -vKg --with-bdeps=n --quiet-build ${PKG_NAME}

    echo '############         Cleaning up            #########'
    rm -rf /var/tmp/portage
    truncate -s0 /etc/portage/binrepos.conf/gentoo-on-steroids.conf

    echo '###########       CONGRATULATIONS !!! EVERYTHING SUCCESSFUL      #######'
EOF

ENV STGUIADDRESS=0.0.0.0:8384
ENV STHOMEDIR=/var/syncthing/config
ENV STNODEFAULTFOLDER=1
ENV STNOUPGRADE=1
ENV HOME=/var/syncthing
VOLUME [ "/var/syncthing" ]
EXPOSE 8384 22000/tcp 22000/udp 21027/udp
ENTRYPOINT [ "/usr/bin/syncthing" ]
