ARG MICROARCH_LEVEL
FROM ghcr.io/rahilarious/gentoo:x86-64-${MICROARCH_LEVEL}

ARG BINHOST_URI
ARG PKG_NAME="llvm-core/clang"

RUN \
    --mount=type=tmpfs,tmpfs-size=100%,dst=/tmp \
    --mount=type=tmpfs,tmpfs-size=100%,dst=/var/tmp \
    --mount=type=tmpfs,tmpfs-size=100%,dst=/var/cache/edb \
    <<-EOF
    #!/usr/bin/bash

    set -e

    if [ -n "${BINHOST_URI}" ]; then
    echo '#####        Configuring binrepos.conf      ######'
    cat <<-EOT | tee -a /etc/portage/binrepos.conf/gentoo-on-steroids.conf
	[gentoo-on-steroids-binpkgserver]
	priority=100
	sync-uri=${BINHOST_URI}
	EOT
    fi
   
    USE=xml emerge -vbgk --with-bdeps=y -o --quiet-build ${PKG_NAME}
    USE=xml emerge -vBgk --with-bdeps=y --quiet-build ${PKG_NAME}
    emerge -c
    USE=xml emerge -vKg --with-bdeps=n --quiet-build ${PKG_NAME}
    echo 'Distcc client is not needed so removing it...'
    rm -v /etc/portage/make.conf/distcc
    sed -i -e '/distcc/Id' /etc/profile.d/01-gentoo-base.sh

    echo '############         Cleaning up            #########'
    rm -rf /var/tmp/portage
    truncate -s0 /etc/portage/binrepos.conf/gentoo-on-steroids.conf

    echo '###########       CONGRATULATIONS !!! EVERYTHING SUCCESSFUL      #######'
EOF

CMD \
    source /etc/profile && \
    echo ${PATH} && \
    /usr/bin/distccd --no-detach --daemon --log-stderr -N 15 -p 3632 --allow-private --log-level warning
