ARG MICROARCH_LEVEL
FROM ghcr.io/rahilarious/gentoo:x86-64-${MICROARCH_LEVEL}

ARG BINHOST_URI

RUN \
    --mount=type=tmpfs,tmpfs-size=100%,dst=/tmp \
    --mount=type=tmpfs,tmpfs-size=100%,dst=/var/tmp \
    --mount=type=tmpfs,tmpfs-size=100%,dst=/var/cache/edb \
    <<-EOF
    #!/usr/bin/bash

    set -e

    echo 'Distcc client is not needed so removing it...'
    rm -v /etc/portage/make.conf/distcc
    sed -i -e '/distcc/Id' /etc/profile.d/01-gentoo-base.sh

    echo '###########       CONGRATULATIONS !!! EVERYTHING SUCCESSFUL      #######'
EOF

CMD \
    source /etc/profile && \
    echo ${PATH} && \
    /usr/bin/distccd --no-detach --daemon --log-stderr -N 15 -p 3632 --allow-private --log-level warning
