ARG MICROARCH_LEVEL
FROM ghcr.io/rahilarious/gentoo:x86-64-${MICROARCH_LEVEL}

ARG BINHOST_URI
ARG PKG_NAME="dev-db/redis"
COPY patches /etc/portage/patches/

RUN \
    --mount=type=tmpfs,tmpfs-size=100%,dst=/tmp \
    --mount=type=tmpfs,tmpfs-size=100%,dst=/var/tmp \
    --mount=type=tmpfs,tmpfs-size=100%,dst=/var/cache/edb \
    \
    if [ -n "${BINHOST_URI}" ]; then \
      echo '#####        Configuring binrepos.conf      ######' && \
      { \
        echo '[gentoo-on-steroids-binpkgserver]'; \
        echo "priority=100"; \
        echo "sync-uri=${BINHOST_URI}"; \
      } | tee -a /etc/portage/binrepos.conf/gentoo-on-steroids.conf; \
    fi && \
    \
    ACCEPT_LICENSE="*" USE="stats" emerge -vbgk --with-bdeps=y -o --quiet-build ${PKG_NAME} && \
    ACCEPT_LICENSE="*" USE="stats" emerge -vBgk --with-bdeps=y --quiet-build ${PKG_NAME} && \
    emerge -c && \
    ACCEPT_LICENSE="*" USE="stats" emerge -vKg --with-bdeps=n --quiet-build ${PKG_NAME} && \
    \
    mkdir -v /data && chown -vR redis:redis /data && \
    \
    echo '############         Cleaning up            #########' && \
    rm -rf /var/tmp/portage && \
    rm /var/log/emerge.log /var/log/portage/elog/summary.log; \
    truncate -s0 /var/log/emerge* /etc/portage/binrepos.conf/gentoo-on-steroids.conf && \
    \
    echo '###########       CONGRATULATIONS !!! EVERYTHING SUCCESSFUL      #######'


VOLUME /data
WORKDIR /data

EXPOSE 6379
CMD [ "/usr/sbin/redis-server" ]

