ARG MICROARCH_LEVEL
FROM ghcr.io/rahilarious/gentoo:x86-64-${MICROARCH_LEVEL}

ARG BINHOST_URI
ARG PKG_NAME="dev-db/redis:0/8.8"
COPY patches /etc/portage/patches/

ADD https://github.com/redis/docker-library-redis/raw/refs/heads/release/8.8/debian/docker-entrypoint.sh /usr/local/bin/
RUN \
    --mount=type=tmpfs,tmpfs-size=100%,dst=/tmp \
    --mount=type=tmpfs,tmpfs-size=100%,dst=/var/tmp \
    --mount=type=tmpfs,tmpfs-size=100%,dst=/var/cache/edb \
    <<-EOF
    #!/usr/bin/bash

    set -e

    if [ -n "${BINHOST_URI}" ]; then
    echo '#####        Configuring binrepos.conf      ######'
    cat <<-EOT | tee -a /etc/portage/binrepos.conf/gentoo-on-steroids.conf
	[gentoo-on-steroids-binpkgserver]
	priority=100
	sync-uri=${BINHOST_URI}
	EOT
    fi
   
    ACCEPT_LICENSE="*" USE="stats" emerge -vbgk --with-bdeps=y -o --quiet-build ${PKG_NAME}
    ACCEPT_LICENSE="*" USE="stats" emerge -vBgk --with-bdeps=y --quiet-build ${PKG_NAME}
    emerge -c
    ACCEPT_LICENSE="*" USE="stats" emerge -vKg --with-bdeps=n --quiet-build ${PKG_NAME}

    mkdir -v /data && chown -vR redis:redis /data /usr/local/bin/docker-entrypoint.sh
    chmod +x /usr/local/bin/docker-entrypoint.sh

    echo '############         Cleaning up            #########'
    rm -rf /var/tmp/portage
    rm /var/log/emerge.log /var/log/portage/elog/summary.log
    truncate -s0 /var/log/emerge* /etc/portage/binrepos.conf/gentoo-on-steroids.conf

    echo '###########       CONGRATULATIONS !!! EVERYTHING SUCCESSFUL      #######'
EOF

WORKDIR /data
ENTRYPOINT ["docker-entrypoint.sh"]
EXPOSE 6379
CMD ["redis-server"]
