ARG MICROARCH_LEVEL
FROM ghcr.io/rahilarious/gentoo:x86-64-${MICROARCH_LEVEL}

ARG BINHOST_URI
ARG PKG_NAME="www-servers/caddy"
COPY patches /etc/portage/patches/
COPY Caddyfile /etc/caddy/Caddyfile

RUN \
    --mount=type=tmpfs,tmpfs-size=100%,dst=/tmp \
    --mount=type=tmpfs,tmpfs-size=100%,dst=/var/tmp \
    \
    if [ -n "${BINHOST_URI}" ]; then \
      echo '#####        Configuring binrepos.conf      ######' && \
      { \
        echo '[gentoo-on-steroids-binpkgserver]'; \
        echo "priority=100"; \
        echo "sync-uri=${BINHOST_URI}"; \
      } | tee -a /etc/portage/binrepos.conf/gentoo-on-steroids.conf; \
    fi && \
    \
    mkdir -pv /srv /config/caddy /data/caddy && \
    chown -v -R 297:297 /srv /config/ /data && \
    emerge -vbgk --with-bdeps=y -o --quiet-build ${PKG_NAME} && \
    emerge -vBgk --with-bdeps=y --quiet-build ${PKG_NAME} && \
    emerge -c && \
    emerge -vKg --with-bdeps=n --quiet-build ${PKG_NAME} && \
    mv -v /usr/share/caddy/index.html /srv/index.html && \
    \
    echo '############         Cleaning up            #########' && \
    rm -rf /var/tmp/portage && \
    rm /var/log/emerge.log /var/log/portage/elog/summary.log && \
    truncate -s0 /var/log/emerge* /etc/portage/binrepos.conf/gentoo-on-steroids.conf && \
    \
    echo '###########       CONGRATULATIONS !!! EVERYTHING SUCCESSFUL      #######'

# See https://caddyserver.com/docs/conventions#file-locations for details
ENV XDG_CONFIG_HOME /config
ENV XDG_DATA_HOME /data

VOLUME [ "/config/", "/data/", "/srv" ]
CMD [  "/usr/bin/caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile" ]
